### PR TITLE
Add default constructor

### PR DESCRIPTION
**Pull request by tractorcow**
See https://github.com/silverstripe/silverstripe-spamprotection/pull/42

### CODE REVIEW

**Comment by dhensby** [comment]
If the base class is going to accept an options array, shouldn't we be adding an options API too? IE: a way to store and access the options?

**Comment by tractorcow** [comment]
The base class is an interface, not a class, so it's really up to the individual implementations of each spam protector to determine how the options are managed internally. :)

I think it should be fine if implementors (as an akismet) simply ignore these values. The only reason for the constructor is to get the breaking change over the line to allow options to be injected in the future (which could then be minor version increments, rather than major).

**Comment by dhensby** [comment]
`trait`?

**Comment by dhensby** [comment]
if you're goal is to pre-empt an API so we can avoid major releases, should't you define the get and set functions as part of that?

**Comment by tractorcow** [comment]
This still needs to support 3.x, so no traits yet. ;D

There is no need to mandate get and set functions as a part of the core API. The goal of this feature is to ensure that the original user-code level configuration is made available to the underlying spam protector. The "what was communicated" is simply an immutable historical fact.

Adding getters and setters would just put additional maintenance burden on the protector implementors that will often just be empty and redundant.

**Comment by robbieaverill** [comment]
Feel free to reopen if you'd still like this change made @tractorcow. Thanks for contributing =)

**Comment by tractorcow** [comment]
Not gonna beat a dead horse. :P

**Pull request closed without merging**
